# Generated by Django 4.1 on 2022-08-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='annee',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='institution',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='matiére',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
