# Generated by Django 4.1 on 2022-08-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_document_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
