# Generated by Django 4.1 on 2022-08-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_document_fichier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='subCategorie',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='categorie',
            new_name='subCategorie',
        ),
    ]
