# Generated by Django 4.1 on 2022-08-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_subcategorie_document_subcategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorie',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification', to='blog.subcategorie'),
        ),
    ]
