# Generated by Django 4.1 on 2022-08-30 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_subcategorie_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorie',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.subcategorie'),
        ),
    ]
