# Generated by Django 4.1 on 2022-09-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_document_institution_alter_document_matiére_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='matiére',
            field=models.CharField(max_length=50),
        ),
    ]
