# Generated by Django 4.1 on 2022-09-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_document_matiére'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='institution',
        ),
        migrations.AddField(
            model_name='document',
            name='institution',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
