# Generated by Django 4.1 on 2022-09-02 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_document_institution_document_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='matiére',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.matiere'),
        ),
    ]
