# Generated by Django 4.1 on 2022-09-02 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_document_annee_alter_document_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Subcategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.subcategorie'),
        ),
    ]
