# Generated by Django 4.1 on 2022-09-04 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_document_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.institution'),
        ),
    ]
