# Generated by Django 4.1 on 2022-09-14 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_document_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorie',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.subcategorie'),
        ),
    ]
